[general]
import = [
  "themes/wombat.toml"
]

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[mouse]
bindings = [
  { mouse = "Right", mods = "Shift", action = "Paste" },

  { mouse = "Left", mods = "Shift", action = "Copy" },
]

# [terminal]
# shell = { program = "/bin/zsh", args = ["--login"] }

[font]
size = 11
[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"

style = "Bold Italic"

[window]
decorations = "full"
opacity = 0.85

[debug]
log_level = "warn"
