require('mason-lspconfig').setup {
    ensure_installed = {
        "pyright",
        "intelephense",
        "vuels",
        "volar",
        "tsserver",
        "terraformls",
        "bashls",
        "dockerls",
        "docker_compose_language_service",
        "yamlls",
        "jsonls",
        "html",
        "cssls",
        "stylelint_lsp",
        "tailwindcss",
        "sqls",
        "lua_ls",
        "eslint",
        "vimls",
    },
}

-- :lua print(vim.inspect(require("mason-lspconfig").get_available_servers()))
-- {
--   "yamlls",
--   "efm",
--   "nil_ls",
--   "pyright",
--   "sqls",
--   "templ",
--   "terraformls",
--   "bashls",
--   "vls",
--   "tinymist",
--   "julials",
--   "starlark_rust",
--   "ruff",
--   "fennel_ls",
--   "lelwel_ls",
--   "volar",
--   "facility_language_server",
--   "bright_script",
--   "lemminx",
--   "esbonio",
--   "cypher_ls",
--   "csharp_ls",
--   "solc",
--   "gopls",
--   "glint",
--   "astro",
--   "clangd",
--   "denols",
--   "asm_lsp",
--   "ltex",
--   "svls",
--   "svlangserver",
--   "stimulus_ls",
--   "standardrb",
--   "sqlls",
--   "spectral",
--   "sourcery",
--   "sorbet",
--   "somesass_ls",
--   "grammarly",
--   "solidity_ls_nomi cfoundation",
--   "apex_ls",
--   "solidity_ls",
--   "gradle_ls",
--   "solang",
--   "ast_grep",
--   "snyk_ls",
--   "golangci_lint_ls",
--   "smithy_ls",
--   "slint_lsp",
--   "serve_d",
--   "fortls",
--   "rust_analyzer",
--   "rubocop",
--   "rome",
--   "robotframework_ls",
--   "flux_lsp",
--   "rnix",
--   "rescriptls",
--   "remark_ls",
--   "regols",
--   "reason_ls",
--   "cmake",
--   "erlangls",
--   "erg_language_server",
--   "docker_compose_language_service",
--   "neocmake",
--   "luau_lsp",
--   "emmet_ls",
--   "puppet",
--   "nimls",
--   "emmet_language_server",
--   "nickel_ls",
--   "cucumber_language_server",
--   "ember",
--   "elp",
--   "elmls",
--   "cssls",
--   "lua_ls",
--   "elixirls",
--   "earthlyls",
--   "dockerls",
--   "drools_lsp",
--   "dprint",
--   "r_language_server",
--   "dotls",
--   "mesonlsp",
--   "diagnosticls",
--   "dhall_lsp_server",
--   "ruff_lsp",
--   "bufls",
--   "motoko_lsp",
--   "dagger",
--   "clojure_lsp",
--   "ocamllsp",
--   "nim_langserver",
--   "marksman",
--   "quick_lint_js",
--   "pyre",
--   "pylyzer",
--   "html",
--   "move_analyzer",
--   "ruby_lsp",
--   "stylelint_lsp",
--   "purescriptls",
--   "cssmodules_ls",
--   "matlab_ls",
--   "psalm",
--   "mutt_ls",
--   "prosemd_lsp",
--   "lexical",
--   "crystalline",
--   "prismals",
--   "thriftls",
--   "markdown_oxide",
--   "powershell_es",
--   "millet",
--   "kotlin_language_server",
--   "cobol_ls",
--   "pkgbuild_language_server",
--   "mdx_analyzer",
--   "tsserver",
--   "pico8_ls",
--   "phpactor",
--   "eslint",
--   "clarity_lsp",
--   "pest_ls",
--   "jsonls",
--   "cairo_ls",
--   "openscad_lsp",
--   "lwc_ls",
--   "bsl_ls",
--   "typst_lsp",
--   "ansiblels",
--   "verible",
--   "ols",
--   "visualforce_ls",
--   "azure_pipelines_ls",
--   "harper_ls",
--   "awk_ls",
--   "jsonnet_ls",
--   "biome",
--   "jqls",
--   "basedpyright",
--   "jinja_lsp",
--   "arduino_language_server",
--   "jedi_language_server",
--   "java_language_server",
--   "hydra_lsp",
--   "angularls",
--   "intelephense",
--   "als",
--   "jdtls",
--   "hoon_ls",
--   "hls",
--   "mm0_ls",
--   "helm_ls",
--   "antlersls",
--   "hdl_checker",
--   "omnisharp",
--   "haxe_language_server",
--   "graphql",
--   "htmx",
--   "beancount",
--   "groovyls",
--   "bicep",
--   "zls",
--   "zk",
--   "codeqlls",
--   "wgsl_analyzer",
--   "coq_lsp",
--   "vuels",
--   "vtsls",
--   "css_variables",
--   "vimls",
--   "pylsp",
--   "vhdl_ls",
--   "custom_elements_ls",
--   "veryl_ls",
--   "vale_ls",
--   "perlnavigator",
--   "vala_ls",
--   "vacuum",
--   "v_analyzer",
--   "unocss",
--   "typos_lsp",
--   "twiggy_language_server",
--   "solidity",
--   "theme_check",
--   "tflint",
--   "texlab",
--   "fennel_language_server",
--   "teal_ls",
--   "taplo",
--   "swift_mesonls",
--   "autotools_ls",
--   "foam_ls",
--   "fsautocomplete",
--   "gitlab_ci_ls",
--   "bzl",
--   "glsl_analyzer",
--   "glslls",
--   "omnisharp_mono",
--   "raku_navigator",
--   "opencl_ls",
--   "salt_ls",
--   "solargraph",
--   "svelte",
--   "tailwindcss"
--   -- }

